[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable", "corepack pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["corepack pnpm --filter @reactify/web build"]

[start]
cmd = "corepack pnpm start:web"
