export const APP_VERSION = "0.1.0" as const;

export const ErrorCode = {
  INVALID_MIME_TYPE: "INVALID_MIME_TYPE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  IMAGE_NOT_FOUND: "IMAGE_NOT_FOUND",
  CORRUPTED_IMAGE: "CORRUPTED_IMAGE",
  UNSUPPORTED_IMAGE: "UNSUPPORTED_IMAGE",
  GENERATION_NOT_FOUND: "GENERATION_NOT_FOUND",
  INVALID_GENERATION_STATE: "INVALID_GENERATION_STATE",
  AI_RESPONSE_VERSION_MISSING: "AI_RESPONSE_VERSION_MISSING",
  ANALYSIS_SCHEMA_INVALID: "ANALYSIS_SCHEMA_INVALID",
  AI_TIMEOUT: "AI_TIMEOUT",
  AI_ERROR: "AI_ERROR",
  GENERATION_SCHEMA_INVALID: "GENERATION_SCHEMA_INVALID",
  GENERATED_PROJECT_SCHEMA_INVALID: "GENERATED_PROJECT_SCHEMA_INVALID",
  PLAN_SCHEMA_INVALID: "PLAN_SCHEMA_INVALID",
  PLAN_PROJECT_MISMATCH: "PLAN_PROJECT_MISMATCH",
  UNSAFE_DEPENDENCY: "UNSAFE_DEPENDENCY",
  UNSAFE_PATH: "UNSAFE_PATH",
  UNSAFE_FILE_PATH: "UNSAFE_FILE_PATH",
  UNSAFE_SOURCE_CODE: "UNSAFE_SOURCE_CODE",
  SANDBOX_REPORT_INVALID: "SANDBOX_REPORT_INVALID",
  SANDBOX_COMPILATION_FAILED: "SANDBOX_COMPILATION_FAILED",
  RUNTIME_VALIDATION_FAILED: "RUNTIME_VALIDATION_FAILED",
  REPORT_TOO_LARGE: "REPORT_TOO_LARGE",
  PATCH_SCHEMA_INVALID: "PATCH_SCHEMA_INVALID",
  PATCH_PATH_INVALID: "PATCH_PATH_INVALID",
  PATCH_SECURITY_VIOLATION: "PATCH_SECURITY_VIOLATION",
  PATCH_DEPENDENCY_INVALID: "PATCH_DEPENDENCY_INVALID",
  PATCH_APPLY_FAILED: "PATCH_APPLY_FAILED",
  REPAIR_NOT_POSSIBLE: "REPAIR_NOT_POSSIBLE",
  REPAIR_ATTEMPTS_EXHAUSTED: "REPAIR_ATTEMPTS_EXHAUSTED",
  REPEATED_PATCH: "REPEATED_PATCH",
  REPEATED_DIAGNOSTICS: "REPEATED_DIAGNOSTICS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface APIErrorBody {
  error: {
    code: ErrorCode;
    message: string;
    requestId: string;
    fieldErrors?: Record<string, string>;
  };
}
